name: build-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: poetry-install
        run: pip install poetry
      - name: make install
        run: make install
      - name: linter-check
        run: make lint